[pytest]
markers =
    positive: Тесты, которые проверяют корректное поведение функции
    negative: Тесты, которые проверяют некорректное поведение функции
[tool.pytest.ini_options]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true